const ACTIONS = {
    LOGIN: 'LOGIN',
    GET_TOKEN: 'GET_TOKEN',
    GET_ADMIN: 'GET_ADMIN',
    GET_GUARDIANS: 'GET_GUARDIANS',
    GET_DOCTORS: 'GET_DOCTORS',
    STATS:'STATS'
}

export default ACTIONS